/**
 * Tiny runtime i18n bridge. Reads the catalog generated by
 * scripts/sync-i18n.cjs (which converts web's lingui .po files) and
 * resolves the active locale from the user's Settings preference.
 *
 * Keys are the English source strings — same convention web uses with
 * lingui. So `t('Today')` returns 'Today' (en) or '今日' (zh).
 *
 * For dynamic strings with placeholders, use `tFmt('{0} days', n)` —
 * lingui-style numbered placeholders, simple sprintf without ICU.
 */

import { I18N_CATALOG } from './i18n-catalog';
import type { Locale } from './i18n-catalog';
import { I18N_EXTRA } from './i18n-extra';

const LANGUAGE_STORAGE_KEY = 'praxys-language';

function readPreference(): 'auto' | 'en' | 'zh' {
  try {
    const stored = wx.getStorageSync<string>(LANGUAGE_STORAGE_KEY);
    if (stored === 'en' || stored === 'zh' || stored === 'auto') return stored;
  } catch {
    /* fall through */
  }
  return 'auto';
}

export function detectLocale(): Locale {
  const pref = readPreference();
  if (pref === 'en' || pref === 'zh') return pref;
  // Auto: ask the WeChat client. wx.getAppBaseInfo (libVersion 2.20.1+)
  // gives us a fresh language code; fall back to getSystemInfoSync on
  // older clients. The mini program is CN-market by design, so anything
  // that isn't an explicit English locale defaults to zh — that's a
  // change from the previous 'en' default. Users on English devices
  // still see English (en_US, en_GB match `^en`); blanks / unknown /
  // WeChat-API failures land on zh.
  try {
    const lang =
      typeof wx.getAppBaseInfo === 'function'
        ? wx.getAppBaseInfo().language ?? ''
        : (wx.getSystemInfoSync().language ?? '');
    return /^en/i.test(lang) ? 'en' : 'zh';
  } catch {
    return 'zh';
  }
}

/**
 * Translate a string. Resolution order:
 *   1. `I18N_EXTRA` — mini-program-local strings (login copy, switch-
 *      account modal, sync-now button, …). Hand-written; takes
 *      precedence so we can override any web translation that doesn't
 *      fit the mini-program voice.
 *   2. `I18N_CATALOG` — auto-synced from web's lingui .po files. The
 *      vast majority of keys live here.
 *   3. The key itself — same fallback as lingui's default behavior.
 */
export function t(key: string): string {
  const locale = detectLocale();
  const extra = I18N_EXTRA[locale]?.[key];
  if (extra != null) return extra;
  const catalog = I18N_CATALOG[locale];
  return catalog?.[key] ?? key;
}

/**
 * Translate with positional placeholders: `{0}`, `{1}`, ...
 *
 * Usage:
 *   tFmt('Targeting {0}{1}', '270', 'W')  →  'Targeting 270W' (en)
 *
 * The original string in the catalog uses lingui's curly-brace syntax,
 * but we keep replacement simple — no ICU plurals here, those come
 * through the .po as separate `_plural` keys we currently drop.
 */
export function tFmt(key: string, ...args: (string | number)[]): string {
  const tpl = t(key);
  return tpl.replace(/\{(\d+)\}/g, (_, i) => {
    const n = parseInt(i, 10);
    return args[n] != null ? String(args[n]) : '';
  });
}
