"""One-time script to cache Garmin OAuth tokens.

Run this once to bootstrap tokens. After that, garmin_sync.py will
reuse the cached tokens and never need to login again.

Usage:
    cd trail-running
    .venv/Scripts/activate
    python -m sync.bootstrap_garmin_tokens
"""
import os
import sys

from dotenv import load_dotenv
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

load_dotenv(os.path.join(os.path.dirname(__file__), ".env"))

TOKEN_DIR = os.path.join(os.path.dirname(__file__), ".garmin_tokens")


def bootstrap_with_credentials():
    """Single login attempt with credentials (no urllib3 retry amplification)."""
    from garminconnect import Garmin

    email = os.environ.get("GARMIN_EMAIL")
    password = os.environ.get("GARMIN_PASSWORD")
    if not email or not password:
        print("Error: GARMIN_EMAIL and GARMIN_PASSWORD must be set in .env")
        return False

    client = Garmin(email, password)

    # Kill urllib3 retries so a 429 fails fast (1 attempt, not 10)
    retry = Retry(total=0, raise_on_status=False)
    adapter = HTTPAdapter(max_retries=retry)
    client.garth.sess.mount("https://", adapter)
    client.garth.sess.mount("http://", adapter)

    print(f"Attempting login for {email} (single attempt, no retries)...")
    try:
        client.login()
        client.garth.dump(TOKEN_DIR)
        print(f"Success! Tokens cached at {TOKEN_DIR}")
        print("garmin_sync.py will now use these automatically.")
        return True
    except Exception as e:
        print(f"Login failed: {e}")
        return False


def bootstrap_with_token_string():
    """Import tokens from a base64 string generated by garth.client.dumps().

    Use this when credential login is blocked (e.g. 429 rate limit).
    Generate the token string on any machine that can reach Garmin:

        pip install garth
        python -c "import garth; garth.login('EMAIL', 'PASS'); print(garth.client.dumps())"

    Then paste the output here.
    """
    import garth

    print("\n--- Token String Import ---")
    print("Generate a token string on any machine that can login to Garmin:\n")
    print('  pip install garth')
    print('  python -c "import garth; garth.login(\'EMAIL\', \'PASS\'); print(garth.client.dumps())"')
    print("\nThen paste the base64 output below.\n")

    token_str = input("Paste token string (or 'skip'): ").strip()
    if token_str.lower() == "skip":
        return False

    try:
        garth.client.loads(token_str)
    except Exception as e:
        print(f"\nFailed to parse token string: {e}")
        print("Make sure you copied the full base64 output from garth.client.dumps().")
        return False

    if not garth.client.oauth1_token or not garth.client.oauth2_token:
        print("\nToken string loaded but missing oauth1 or oauth2 tokens.")
        return False

    os.makedirs(TOKEN_DIR, exist_ok=True)
    garth.client.dump(TOKEN_DIR)
    print(f"\nSuccess! Tokens cached at {TOKEN_DIR}")
    print("garmin_sync.py will now use these automatically.")
    return True


if __name__ == "__main__":
    print("=== Garmin Token Bootstrap ===\n")

    if os.path.exists(os.path.join(TOKEN_DIR, "oauth1_token.json")):
        print(f"Tokens already exist at {TOKEN_DIR}")
        resp = input("Overwrite? (y/N): ").strip().lower()
        if resp != "y":
            sys.exit(0)

    # Try credential login first
    if bootstrap_with_credentials():
        sys.exit(0)

    print("\nCredential login failed (likely 429 rate limit).")
    print("You can import tokens from another machine instead.\n")

    choice = input("Try token string import? (Y/n): ").strip().lower()
    if choice != "n":
        if bootstrap_with_token_string():
            sys.exit(0)

    print("\nRe-run this script later when the rate limit clears.")
