from pathlib import Path

PAIRS = [
    # Settings page
    ("Settings", "设置"),
    ("Configure your training system", "配置您的训练系统"),
    ("Viewing configuration (read-only demo)", "查看配置（只读演示）"),
    ("Profile", "个人资料"),
    ("Your identity in Trainsight", "您在 Trainsight 的身份"),
    ("Your name", "您的名字"),
    ("Failed to load settings", "加载设置失败"),
    ("Connected Platforms", "已连接平台"),
    ("Link your training devices and services", "关联您的训练设备与服务"),
    ("Hide backfill", "隐藏回填"),
    ("Backfill...", "回填..."),
    ("Sync All", "全部同步"),
    ("Sync from:", "同步起始日期："),
    ("Backfill All", "全部回填"),
    ("Clear", "清除"),
    ("Historical sync may take several minutes", "历史同步可能需要几分钟"),
    ("Auto sync frequency", "自动同步频率"),
    ("How often Trainsight pulls new data in the background. Lower frequency uses less network and respects platform rate limits.",
     "Trainsight 后台拉取新数据的频率。较低频率占用更少网络流量，并尊重平台的速率限制。"),
    ("Next sync", "下次同步"),
    ("Every <0>{option.hours}</0> hours", "每 <0>{option.hours}</0> 小时"),
    ("recommended", "推荐"),
    ("Connected", "已连接"),
    ("Not connected", "未连接"),
    ("Syncing", "同步中"),
    ("Synced", "已同步"),
    ("Error", "错误"),
    ("Sync", "同步"),
    ("Region", "地区"),
    ("International", "国际"),
    ("China", "中国"),
    ("Disconnect", "断开连接"),
    ("Training Base", "训练基准"),
    ("How your zones and training load are calculated", "如何计算您的区间与训练负荷"),
    ("Data Preferences", "数据偏好"),
    ("Choose which platform to use for each data type", "为每种数据类型选择使用的平台"),
    ("Fitness", "体能"),
    ("VO2max, CP, LTHR, training status", "VO2max、CP、LTHR、训练状态"),
    ("Auto-merged", "自动合并"),
    ("Target a race or track continuous improvement", "瞄准一场比赛或追踪持续提升"),
    ("Set goal", "设定目标"),
    ("Edit", "编辑"),
    ("Mode", "模式"),
    ("Race Goal", "比赛目标"),
    ("Continuous Improvement", "持续提升"),
    ("Distance", "距离"),
    ("Race Date", "比赛日期"),
    ("Target Time", "目标时间"),
    ("No goal set. Set a race target or distance goal to unlock predictions and countdown.",
     "尚未设定目标。设定比赛目标或距离目标以解锁预测与倒计时。"),
    ("Thresholds", "阈值"),
    ("Drive your zone calculations and training load. Click to override.",
     "驱动您的区间计算与训练负荷。点击可覆盖。"),
    ("Critical Power", "临界功率"),
    ("LTHR", "乳酸阈心率"),
    ("Threshold Pace", "阈值配速"),
    ("Max HR", "最大心率"),
    ("Resting HR", "静息心率"),
    ("Save", "保存"),
    ("Cancel", "取消"),
    ("Not set", "未设置"),
    ("Auto", "自动"),
    ("Manual", "手动"),
    ("Power", "功率"),
    ("Heart Rate", "心率"),
    ("Pace", "配速"),
    ("Zones & load from Critical Power", "基于临界功率的区间与负荷"),
    ("Zones & load from Lactate Threshold HR", "基于乳酸阈心率的区间与负荷"),
    ("Zones & load from Threshold Pace", "基于阈值配速的区间与负荷"),
    ("Primary source for workout data", "训练数据的主要来源"),
    ("Sleep, HRV, readiness", "睡眠、HRV、恢复度"),
    ("Training plan & targets", "训练计划与目标"),
    ("Plan", "计划"),
    ("Primary for {0}", "作为 {0} 的主要来源"),
    ("Last synced {0}", "上次同步 {0}"),
    # Distance labels
    ("Marathon", "马拉松"),
    ("Half Marathon", "半程马拉松"),
    ("5K", "5公里"),
    ("10K", "10公里"),
    ("50K", "50公里"),
    ("50 Mile", "50英里"),
    ("100K", "100公里"),
    ("100 Mile", "100英里"),
    # Display labels via tDisplay
    ("Recovery", "恢复"),
    ("Endurance", "耐力"),
    ("Tempo", "节奏"),
    ("Threshold", "乳酸阈"),
    ("VO2max", "VO2max"),
    ("Lactate Threshold HR", "乳酸阈心率"),
    ("CP Trend", "CP 趋势"),
    ("LTHR Trend", "LTHR 趋势"),
    ("Threshold Pace Trend", "阈值配速趋势"),
    # Dynamic Goal/Training strings
    ("Peak Interval {intensityLabel}", "峰值间歇 {intensityLabel}"),
    ("Avg Work {intensityLabel}", "平均工作 {intensityLabel}"),
    ("{topZoneName} / Quality", "{topZoneName} / 质量"),
    ("Predicted {distLabel}", "预测 {distLabel}"),
    ("{distLabel} Countdown", "{distLabel} 倒计时"),
    ("{distLabel} Progress", "{distLabel} 进度"),
    ("days until {0}", "距 {0} 还有"),
    ("Building toward {0} {distLabel}", "朝着 {0} {distLabel} 努力"),
    ("Current {abbrev}", "当前 {abbrev}"),
    ("Needed {abbrev}", "所需 {abbrev}"),
    ("Gap", "差距"),
    ("Realistic Alternative Targets", "现实的替代目标"),
    ("Comfortable", "轻松目标"),
    ("Stretch", "挑战目标"),
    ("Reality Check", "现实评估"),
    ("Fitness Trend", "体能趋势"),
    ("Estimated time to target", "达到目标预计时间"),
    ("{0} months", "{0} 个月"),
    # Page titles repeated
    ("Goal Tracker", "目标追踪"),
    ("Change Goal", "修改目标"),
    ("Training Insights", "训练洞察"),
    ("Weekly Review", "周度回顾"),
    ("Training Diagnosis", "训练诊断"),
    ("Weekly Volume", "周里程"),
    ("Suggestions", "建议"),
    ("Training Science", "训练科学"),
    # DataHint / CliHint common
    ("Not enough data for accurate form tracking", "数据不足以准确追踪状态"),
    ("Sync at least 6 weeks of activity data to see your training form trend.",
     "至少同步 6 周的活动数据以查看训练状态趋势。"),
    ("Not enough data for accurate fitness tracking", "数据不足以准确追踪体能"),
    ("Sync at least 6 weeks of activity data to see meaningful fitness, fatigue, and form curves.",
     "至少同步 6 周的活动数据以查看有意义的体能、疲劳和状态曲线。"),
    ("Not enough data to show CP trend", "数据不足以显示 CP 趋势"),
    ("Need at least 3 activities with power data to plot a meaningful trend.",
     "需要至少 3 次带功率数据的活动才能绘制有意义的趋势。"),
    ("Need at least 3 activities with power data.", "需要至少 3 次带功率数据的活动。"),
    ("Not enough data for weekly load comparison", "数据不足以进行周负荷对比"),
    ("Sync at least 2 weeks of data to compare planned vs actual training load.",
     "至少同步 2 周的数据以对比计划与实际训练负荷。"),
    ("Not enough data to show sleep vs performance", "数据不足以显示睡眠与表现对比"),
    ("Connect a recovery source (like Oura Ring) and sync activities with power data.",
     "连接恢复数据源（如 Oura Ring）并同步带功率数据的活动。"),
    ("AI Daily Brief", "AI 每日简报"),
    ("Get personalized training recommendations, recovery assessment, and today's training signal with the Claude Code plugin.",
     "通过 Claude Code 插件获取个性化训练建议、恢复评估及今日训练信号。"),
    ("AI Training Analysis", "AI 训练分析"),
    ("Get in-depth zone distribution analysis, training suggestions, and a personalized plan generated by AI.",
     "获取深入的区间分布分析、训练建议及 AI 生成的个性化计划。"),
    ("Generate Training Plan", "生成训练计划"),
    ("Create a science-based 4-week training plan tailored to your fitness, recovery, and goals.",
     "创建基于科学、契合您的体能、恢复与目标的 4 周训练计划。"),
    ("AI Race Forecast", "AI 比赛预测"),
    ("Get a detailed race prediction, goal feasibility analysis, and what you need to improve.",
     "获取详细的比赛预测、目标可行性分析，以及您需要改进的方面。"),
    # ZoneAnalysisCard
    ("Zone Analysis", "区间分析"),
    ("Distribution deviates from target", "分布偏离目标"),
    ("Zone", "区间"),
    ("Range", "范围"),
    ("Actual", "实际"),
    ("Target", "目标"),
    ("above", "高于"),
    ("below", "低于"),
    ("target", "目标"),
    # Misc
    ("Retry", "重试"),
    ("How this is calculated", "计算方法"),
    ("Source", "来源"),
    ("Discussion", "讨论"),
]

path = Path("web/src/locales/zh/messages.po")
content = path.read_text(encoding="utf-8")
count = 0
for src, tgt in PAIRS:
    esc = src.replace("\\", "\\\\").replace('"', '\\"')
    pattern_a = f'msgid "{esc}"\nmsgstr ""'
    replacement_a = f'msgid "{esc}"\nmsgstr "{tgt}"'
    if pattern_a in content:
        content = content.replace(pattern_a, replacement_a, 1)
        count += 1
path.write_text(content, encoding="utf-8")
print(f"Seeded additional {count}/{len(PAIRS)} translations")
