from pathlib import Path

PAIRS = [
    ("Get the Claude Code Plugin", "获取 Claude Code 插件"),
    ("How this is calculated", "计算方法"),
    ("Source", "来源"),
    ("Discussion", "讨论"),
    # Chart axis labels
    ("Sleep Score", "睡眠评分"),
    ("Avg Power (W)", "平均功率 (W)"),
    ("Actual rTSS", "实际 rTSS"),
    ("Planned rTSS", "计划 rTSS"),
    # Misc
    ("AI Daily Brief", "AI 每日简报"),
    ("AI Training Analysis", "AI 训练分析"),
    ("AI Race Forecast", "AI 比赛预测"),
    ("Generate Training Plan", "生成训练计划"),
    # Today page — remaining untranslated
    ("Warnings", "警告"),
    ("Last Activity", "上次活动"),
    ("Weekly Load", "周训练负荷"),
    ("Planned Workout", "计划训练"),
    ("No Workout", "无训练"),
    ("Coming Up", "即将到来"),
    ("Options", "选项"),
    # Workout phases
    ("Warmup", "热身"),
    ("Cooldown", "放松"),
    ("Main", "主训练"),
    ("Easy Run", "轻松跑"),
    ("Steady", "匀速"),
    ("Aerobic", "有氧"),
    ("Tempo", "节奏跑"),
    ("Rest", "休息"),
    ("Rep", "组"),
    ("Run", "跑步"),
    # RecoveryPanel remaining
    ("7d Trend", "7天趋势"),
    ("Baseline", "基线"),
    ("Other Signals", "其他信号"),
    ("High variability", "变异性偏高"),
    # More stuff seen
    ("Race", "比赛"),
    ("Backfill All", "全部回填"),
    ("Clear", "清除"),
    ("Start sync", "开始同步"),
    ("Syncing", "同步中"),
    ("Synced", "已同步"),
    ("Error", "错误"),
    ("Sync", "同步"),
    ("Historical sync may take several minutes", "历史同步可能需要几分钟"),
    ("Viewing configuration (read-only demo)", "查看配置（只读演示）"),
    # Trend
    ("Rising", "上升"),
    ("Falling", "下降"),
    ("Flat", "持平"),
    # Goal page extra
    ("Predicted {distLabel}", "预测 {distLabel}"),
    ("Realistic Alternative Targets", "现实的替代目标"),
    ("Fitness Trend", "体能趋势"),
    ("Estimated time to target", "达到目标预计时间"),
    # Setup page remaining
    ("Set up Trainsight", "设置 Trainsight"),
    ("Complete these steps to unlock your training insights", "完成这些步骤以解锁您的训练洞察"),
    ("Connect a platform first", "请先连接一个平台"),
    ("Choose how much historical data to pull", "选择要拉取的历史数据量"),
    ("Link at least one data source to start", "至少关联一个数据源以开始"),
    ("Sync history", "同步历史"),
    ("Sync complete! Your data is ready.", "同步完成！数据已就绪。"),
    ("Data synced successfully", "数据同步成功"),
    ("Will sync:", "将同步："),
    ("Race Goal configured", "已配置比赛目标"),
    ("Continuous improvement configured", "已配置持续提升"),
    ("Race goal configured", "已配置比赛目标"),
    ("Go to dashboard", "前往仪表盘"),
    ("Skip for now", "暂时跳过"),
    ("Cross-training activities affect your overall training load and recovery",
     "交叉训练活动会影响您的整体训练负荷与恢复"),
    ("Choose primary source", "选择主要数据源"),
    ("Optional — you can always set this later from the Goal page",
     "可选——您随时可以从目标页面设置"),
    # Admin page
    ("Admin", "管理"),
    ("Manage users and invitation codes", "管理用户与邀请码"),
    ("Users", "用户"),
    ("Registered accounts", "注册账户"),
    ("Role", "角色"),
    ("Registered", "注册于"),
    ("Actions", "操作"),
    ("Invitation Codes", "邀请码"),
    ("One-time codes for new user registration", "用于新用户注册的一次性邀请码"),
    ("Generate", "生成"),
    ("Note (optional)", "备注（可选）"),
    ("Used", "已使用"),
    ("Available", "可用"),
    ("Revoked", "已撤销"),
    ("Revoke", "撤销"),
    ("No invitation codes yet. Generate one to invite a user.", "尚无邀请码。生成一个以邀请用户。"),
    ("New invitation code:", "新邀请码："),
    ("Demo Accounts", "演示账号"),
    ("Read-only accounts that mirror your dashboard data", "镜像您仪表盘数据的只读账号"),
    ("Click to copy", "点击复制"),
    ("you", "您"),
    ("Demo", "演示"),
    ("User", "用户"),
    ("Promote", "提升"),
    ("Demote", "降级"),
    ("Promote to Admin", "提升为管理员"),
    ("Demote to User", "降级为普通用户"),
    ("Delete User", "删除用户"),
    ("Deleting...", "删除中..."),
    ("Updating...", "更新中..."),
    # History page
    ("Activities", "活动"),
    ("No activities found.", "未找到活动。"),
    ("Failed to load activities", "加载活动失败"),
    ("Previous", "上一页"),
    ("Next", "下一页"),
    ("Showing", "显示"),
    ("of", "共"),
    ("Distance", "距离"),
    ("Duration", "时长"),
    ("Avg Power", "平均功率"),
    ("Avg HR", "平均心率"),
    ("Pace", "配速"),
    ("Elev", "爬升"),
    # Science page
    ("Training Science", "训练科学"),
    ("Four pillars power your analysis. Each uses a published theory you can understand, verify, and change.",
     "四大支柱驱动您的分析。每一支柱都采用可理解、可验证、可更改的已发表理论。"),
    ("Load & Fitness", "负荷与体能"),
    ("How does training stress become fitness?", "训练应激如何转化为体能？"),
    ("How do we assess readiness to train?", "如何评估训练准备度？"),
    ("Race Prediction", "比赛预测"),
    ("How do we estimate race potential?", "如何估算比赛潜力？"),
    ("Training Zones", "训练区间"),
    ("How is intensity classified?", "如何分类训练强度？"),
    ("Active", "当前使用"),
    ("Simple", "简要"),
    ("Advanced", "详细"),
    ("Use this", "使用此项"),
    ("References", "参考文献"),
    ("Zone Labels", "区间标签"),
    ("Cosmetic \u2014 changes names and colors without affecting calculations",
     "仅外观——更改名称与颜色，不影响计算"),
    ("view", "查看"),
    ("Failed to load science data", "加载科学数据失败"),
]

path = Path("web/src/locales/zh/messages.po")
content = path.read_text(encoding="utf-8")
count = 0
for src, tgt in PAIRS:
    esc = src.replace("\\", "\\\\").replace('"', '\\"')
    pattern = f'msgid "{esc}"\nmsgstr ""'
    replacement = f'msgid "{esc}"\nmsgstr "{tgt}"'
    if pattern in content:
        content = content.replace(pattern, replacement, 1)
        count += 1
path.write_text(content, encoding="utf-8")
print(f"Seeded additional {count}/{len(PAIRS)} translations")
